# Generated by Django 3.1.7 on 2021-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('shape', models.CharField(choices=[('Square', 'Square'), ('Circle', 'Circle'), ('Oval', 'Oval')], max_length=100)),
                ('width', models.IntegerField()),
                ('heigh', models.IntegerField()),
                ('doors', models.ManyToManyField(to='rooms.Door')),
            ],
        ),
    ]
