# Generated by Django 3.1.7 on 2021-03-06 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='heigh',
            new_name='height',
        ),
    ]
