# Generated by Django 3.1.7 on 2021-05-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20210305_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='door',
            name='wall',
            field=models.IntegerField(default=0),
        ),
    ]
