# Generated by Django 3.1.7 on 2021-06-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210522_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='location',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='wall',
            field=models.IntegerField(choices=[(0, 'North'), (1, 'East'), (2, 'South'), (3, 'West')], default=0, null=True),
        ),
    ]
